; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- BASIS-KONFIGURATION (Gilt für alle Nodes) ---
[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
build_flags = -Wall -Wextra
lib_deps = 
    bertmelis/espMqttClient@^1.7.3

; --- NODE 1: BME688 & SCD41 ---
[env:node_bme688_scd41]
build_flags = 
    -D NODE_TOPIC='"flat/bedroom/state"'
build_src_filter = +<*> -<sensors_*.cpp> +<sensors_bme688_scd41.cpp>
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit BME680 Library@^2.0.6
    sensirion/Sensirion I2C SCD4x@^1.1.0

; --- NODE 2: PMSA003I & BME280 ---
[env:node_pmsa_bme280]
build_flags = 
    -D NODE_TOPIC='"flat/balcony/state"'
build_src_filter = +<*> -<sensors_*.cpp> +<sensors_bme280_pmsa003i.cpp>
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit BME280 Library@^2.3.0
    adafruit/Adafruit PM25 AQI Sensor@^2.0.0
    